export interface Cameras {
    camera_id: number,
    name: string,
    physical_address: string,
    is_registered: number,
    direction: null| string,
    organization_id: string,
    folder_id: null | string,
    hub_id: string,
    rtsp_url: string,
    webrtc_url: string,
    is_record: number,
    is_ai_stream_active: number,
    is_intrusion_active: number,
    is_people_count_active: number,
    is_motion_event_active: number,
    is_license_plate_detection_active: number,
    people_threshold_count: number,
    created_at: string,
    updated_at: string
}