import type { Metadata } from "next";
import "../styles/globals.css";
import { Providers } from "@/providers/Providers";
import { jakarta } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      {/* suppressHydrationWarning */}
      <body className={`${jakarta.variable} antialiased bg-[var(--surface-150)]`}>
        <Providers>
          {children} {/* This will render either auth or app layout */}
        </Providers>
      </body>
    </html>
  );
}
