name: build-and-push
on: { push: { branches: [main] } }

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/kapidhwaj-ai/kapidhwaj-web:latest
          cache-from: type=registry,ref=ghcr.io/kapidhwaj-ai/kapidhwaj-web:cache
          cache-to: type=registry,ref=ghcr.io/kapidhwaj-ai/kapidhwaj-web:cache,mode=max
